### PR TITLE
Display unread count on folder view

### PR DESCRIPTION
**Pull request by lucas8**
Display the number of unread messages in a folder :
    1071 (  5) folder (tags)

Inspired by notmuch-mutt.

### CODE REVIEW

**Comment by ff2000** [comment]
Thx for the pull request! Looks great.
Two small issues:
* I think "unreads" doesn't exist in english. Imho it should be "notmuch_folders_count_unread", or even "notmuch_folders_display_unread_count". But I am not a native english speaker, so I may be wrong ;)
* IMHO it should also take "notmuch_folders_count_threads" into account. It is a heavier operation but at least I would expect it.

I would like to know what @imain thinks about those two points.

**Comment by lucas8** [comment]
Concerning the first issue, I'm not an english speaker either, so I wont change it for now (let's wait for someone who knows).
The second issue is something I hesitated doing, but I felt it would be more useful to have the number of unread messages rather than the number of threads with unread messages, but if you think otherwise, it will quite easy to add.

**Comment by ff2000** [comment]
I think we waited long enough.
First off I had a look at gmail's web interface: They also show unread thread count when enabling conversations. Thunderbird on the other hand does not, but TB is not really a conversation-centric mail client. I don't have other mail clients around, but I think it's better to show thread count instead of message count - which you already changed :)

Concerning the naming:
In English you usually don't modify adjectives when used for plural ("unread messages" instead of "unreads messages") - not like in French or German.
"notmuch_folders_count_unread" IMHO is also not good as it might sound like an alternative to "notmuch_folders_count_threads".
So I would vote for either "notmuch_folders_display_unread" or "notmuch_folders_display_unread_count" (with slight preference for the second, but I leave it to you).

Besides that I don't have any objections and will merge after the naming change.

**Comment by ff2000** [comment]
Thx alot! Really nice feature :)

**Pull request merged**
