### PR TITLE
Add support for gpg signed and crypted mail

### PR DESCRIPTION
**Pull request by lucas8**
Add support for encrypted mails and verify signed ones using mail-gpg.
I don't recommend merging it yet, as I have noticed a few bugs. I made this pull request to have feedback about the feature.

### CODE REVIEW

**Comment by lucas8** [comment]
I got everything working except for the passphrass input. Futhermore, I only have gnupg 2.1 on my computer, so I won't test it with gnupg 1.x and gnupg 2.0

**Comment by lucas8** [comment]
Everything works under gpg 2.1 with the pinentry input method. I couldn't get the gpg_passfunc to work, and I won't have time to get it to work (hollidays end tomorrow).
If we exclude this problem, I consider this pull request mature enough to be merged.

**Comment by tgirod** [comment]
:+1:  I've just tried it - so far, so good ! 
@imain, will you consider pulling this ?

**Comment by ff2000** [comment]
Thx @lucas8 for this feature and @tgirod for testing!

**Pull request merged**
